model_names:
  - unet

model:
  unet:
    checkpoint_path: "/Workspace/Users/fabian.heflo@kartverket.no/Snuplasser/src/1210512690420640/61596b71a35845fa947b304eb966d3e9/checkpoints/epoch=08-val_loss=0.2453.ckpt"
    encoder: resnet18
    encoder_weights: imagenet
    in_channels: 4
    num_classes: 1

data:
  image_dir: /Volumes/land_topografisk-gdb_dev/external_dev/static_data/DL_SNUPLASSER/endepunkt_images/
  dom_dir: /Volumes/land_topografisk-gdb_dev/external_dev/static_data/DL_SNUPLASSER/endepunkt_dom/
  batch_size: 8
  num_workers: 4
  use_augmentation: false

predict:
  output_dir: predictions/unlabeled_test   # Hvor pred maskene skal lagres
  save_format: png                         # Kan også være numpy etc.
  threshold: 0.5                           # Brukes for binarisering av output

logging:
  use_mlflow: true
  experiment_name: /Users/fabian.heflo@kartverket.no/unlabeled_test_unet
  #tracking_uri: "val_predictions"
