
model_names:
  - unet
  - deeplabv3

model:
  unet:
    lr: 0.001
    encoder: resnet64
    num_classes: 2

  deeplabv3:
    lr: 0.0005
    backbone: mobilenet
    num_classes: 2

data:
  image_dir: /Volumes/land_topografisk-gdb_dev/external_dev/static_data/DL_SNUPLASSER/img/
  mask_dir: /Volumes/land_topografisk-gdb_dev/external_dev/static_data/DL_SNUPLASSER/lab/
  dom_dir: /Volumes/land_topografisk-gdb_dev/external_dev/static_data/DL_SNUPLASSER/dom/
  batch_size: 8               # Default (overstyres av Optuna)
  num_workers: 4              # DataLoader workers
  val_split: 0.2              # Valideringsandel (f.eks. 20%)
  holdout_size: 5
  seed: 42
  use_augmentation: false
  augmentation_ratio: 0.3


training:
  max_epochs: 30              # Antall epoker per kjøring
  precision: 16               # Mixed precision (16 eller 32)
  accelerator: gpu
  devices: 1                  # GPU-ressurser
  early_stopping_patience: 5  # Stopper tidlig om validerings-loss ikke forbedres
  monitor: val_loss  # val_IoU , Må logges av modellen og oppdateres i utils.callbacks
  monitor_mode: min  # max for IoU

logging:
  use_mlflow: true
  experiment_name: optuna_unet
  tracking_uri: file:./mlruns

optuna:
  direction: maximize         # Hvilken vei metrikken skal optimaliseres
  metric_name: val_IoU        # Navn på metrikken som returneres fra validate()
  n_trials: 30                # Antall eksperimenter