
model_names:
  #- unet
  #- deeplabv3
  - deeplabv3plus
  


model:
  unet:
    encoder: mobilenet_v2
    encoder_weights: imagenet
    in_channels: 4
    num_classes: 1
    lr: 0.001


  deeplabv3:
    backbone: resnet18 #mobilenet_v2
    in_channels: 4
    num_classes: 1
    lr: 0.001


  deeplabv3plus:
    backbone: resnet34
    in_channels: 4
    num_classes: 1
    lr: 0.001

data:
  image_dir: /Volumes/land_topografisk-gdb_dev/external_dev/static_data/DL_SNUPLASSER/img/
  mask_dir: /Volumes/land_topografisk-gdb_dev/external_dev/static_data/DL_SNUPLASSER/lab/
  dom_dir: /Volumes/land_topografisk-gdb_dev/external_dev/static_data/DL_SNUPLASSER/dom/
  batch_size: 8               # Default (overstyres av Optuna)
  num_workers: 4              # DataLoader workers
  val_split: 0.2              # Valideringsandel (f.eks. 20%)
  holdout_size: 5
  seed: 42
  use_augmentation: true
  augmentation_ratio: 0.4
  flip_p: 0.3
  brightness_limit: 0.05
  contrast_limit: 0.05
  rotate_limit: 10
  scale_limit: 0.05
  gaussian_blur_p: 0.1
  elastic_transform_p: 0.1

  normalize:
    mean: [0.485, 0.456, 0.406, 0.5]
    std: [0.229, 0.224, 0.225, 0.25]
  


training:
  max_epochs: 10              # Antall epoker per kjøring
  precision: 16      # Mixed precision (16 eller 32)
  accelerator: gpu
  devices: 1                  # GPU-ressurser
  early_stopping_patience: 5  # Stopper tidlig om validerings-loss ikke forbedres
  monitor: val_loss  # val_IoU , Må logges av modellen og oppdateres i utils.callbacks
  monitor_mode: min  # max for IoU

log_predictions_callback:
  log_every_n_epochs: 2
  artifact_dir: "val_predictions"
  always_log_ids:
    - "image_252063_6774942_252131_6775008.png"
    - "image_267985_6778930_268055_6779021.png"
    - "image_270356_6771602_270421_6771665.png"

logging:
  use_mlflow: true
  #experiment_name: /Users/fabian.heflo@kartverket.no/deeplabv3_resnet50
  experiment_name: /Users/enes.topcu@kartverket.no/deeplabv3_resnet50_retrain
  tracking_uri: "databricks" # Slik at eksperimenter og modeller kan lagres og sammenlignes sentralt

optuna:
  direction: maximize         # Hvilken vei metrikken skal optimaliseres
  metric_name: val_IoU        # Navn på metrikken som returneres fra validate()
  n_trials: 30                # Antall eksperimenter