name: Black Code Formatter

on:
  push:
    branches:
      - main
      - gitHub_Actions

  pull_request:
    branches:
      - main 
      - gitHub_Actions

jobs:
  black-check:
    name: Black Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Upgrade pip
        run: python -m pip install -- upgrade pip

      - name: Install black
        run: pip install black

      - name: Run black
        run: black --check .
