name: PyTorch Linter
on:
  push:
    branches: 
        - "*"
  pull_request:
    branches: 
        - main
jobs:
  lint:
    name: Run PyTorch Linting (pylint)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pylint
          pip install -r requirements.txt  # varsa

      - name: Run pylint on PyTorch files only
        run: pylint lightning_model.py model.py unet.py utils.py main.py